'use client';

import { useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, BookOpen, ChevronDown, CircleHelp, Clock3, Gauge, Layers3, LineChart, Play, Radio, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, TerminalSquare, Zap } from 'lucide-react';

const prints = [
  ['09:41:00','buy','182.41','420','XNAS'],['09:41:03','sell','182.40','185','BATS'],
  ['09:41:07','buy','182.42','760','XNAS'],['09:41:13','buy','182.43','220','EDGX'],
  ['09:41:18','sell','182.42','510','XNAS'],['09:41:25','buy','182.44','340','ARCX'],
];
const book = [['182.46',530,'ask'],['182.45',286,'ask'],['182.44',712,'ask'],['182.43',460,'ask'],['182.42',890,'mid'],['182.41',650,'bid'],['182.40',480,'bid'],['182.39',920,'bid'],['182.38',760,'bid']];
const venueQuotes = [['XNAS','182.41','182.43','0.9ms','62%'],['BATS','182.40','182.42','1.2ms','48%'],['EDGX','182.41','182.44','1.5ms','31%'],['ARCX','182.40','182.43','1.8ms','22%']];
const chartPaths: Record<'1m'|'5m'|'30m', string> = { '1m': '0,104 46,101 92,108 138,91 184,94 230,82 276,88 322,71 368,76 414,61 460,66 506,51 552,56 598,39 644,44 690,29', '5m': '0,148 46,135 92,141 138,115 184,122 230,96 276,104 322,79 368,88 414,60 460,66 506,38 552,50 598,25 644,32 690,14', '30m': '0,132 46,119 92,125 138,138 184,111 230,102 276,113 322,88 368,96 414,73 460,84 506,57 552,64 598,46 644,52 690,22' };
const chartTicks: Record<'1m'|'5m'|'30m', string[]> = { '1m': ['09:41:00','09:41:15','09:41:30','09:41:45','09:42:00'], '5m': ['09:36:00','09:37:30','09:39:00','09:40:30','09:42:00'], '30m': ['09:12:00','09:19:30','09:27:00','09:34:30','09:42:00'] };

function Metric({ label, value, note, tone = '' }: { label: string; value: string; note: string; tone?: string }) {
  return <div className="metric-card"><div className="eyebrow">{label}</div><div className={'metric-value ' + tone}>{value}</div><div className="metric-note">{note}</div></div>;
}

export default function Home() {
  const [window, setWindow] = useState<'1m'|'5m'|'30m'>('5m');
  const [mode, setMode] = useState<'TWAP'|'VWAP'|'POV'>('TWAP');
  const [side, setSide] = useState<'Buy'|'Sell'>('Buy');
  const [benchmark, setBenchmark] = useState<'Arrival'|'VWAP'|'Close'>('Arrival');
  const [quantity, setQuantity] = useState(25000);
  const [horizon, setHorizon] = useState(15);
  const [participation, setParticipation] = useState(10);
  const [routePolicy, setRoutePolicy] = useState<'Balanced'|'Queue-aware'|'Latency-aware'>('Balanced');
  const [maxSpread, setMaxSpread] = useState(3);
  const [run, setRun] = useState(1);
  const [history, setHistory] = useState<Array<{ id: number; strategy: string; side: string; benchmark: string; slippage: string; fill: string }>>([]);
  const [replayIndex, setReplayIndex] = useState(5);
  const [printFilter, setPrintFilter] = useState<'All'|'Buys'|'Sells'>('All');
  const activePrint = prints[replayIndex];
  const visiblePrints = printFilter === 'All' ? prints : prints.filter(([, printSide]) => printSide === printFilter.slice(0, -1).toLowerCase());
  const result = useMemo(() => {
    const scale = Math.min(quantity / 25000, 3);
    const benchmarkAdj = benchmark === 'VWAP' ? -0.6 : benchmark === 'Close' ? 1.1 : 0;
    const sideAdj = side === 'Sell' ? 0.25 : 0;
    const modeFactor = mode === 'TWAP' ? 1.8 : mode === 'VWAP' ? 1.35 : 1.05;
    const participationAdj = mode === 'POV' ? (participation / 10) * .65 : 0;
    const venueMix = (routePolicy === 'Queue-aware' ? [['XNAS','49%','teal'],['BATS','28%','blue'],['EDGX','15%','orange'],['ARCX','8%','faint']] : routePolicy === 'Latency-aware' ? [['XNAS','55%','teal'],['BATS','26%','blue'],['EDGX','13%','orange'],['ARCX','6%','faint']] : [['XNAS','42%','teal'],['BATS','31%','blue'],['EDGX','17%','orange'],['ARCX','10%','faint']]);
    const quotedSpread = 2.0;
    const spreadCheck = quotedSpread <= maxSpread;
    const bookCoverage = quantity <= 50000;
    const checks = [{ label: 'Spread guard', value: spreadCheck ? 'PASS' : 'HOLD', detail: quotedSpread.toFixed(1) + '¢ inside ' + maxSpread.toFixed(1) + '¢ limit', tone: spreadCheck ? 'good' : 'warn' }, { label: 'Book coverage', value: bookCoverage ? 'COVERED' : 'STRETCHED', detail: bookCoverage ? 'Top venues cover the working clip' : 'Split the parent order before routing', tone: bookCoverage ? 'good' : 'warn' }, { label: 'Route posture', value: routePolicy.toUpperCase(), detail: mode === 'POV' ? participation + '% participation cap' : mode + ' schedule', tone: 'good' }];
    const baseSlippage = 4.7 + scale * modeFactor + participationAdj + (horizon < 10 ? 1.9 : 0) + sideAdj;
    const slippage = Math.max(.8, baseSlippage + benchmarkAdj).toFixed(1);
    const spread = mode === 'TWAP' ? 1.2 : mode === 'VWAP' ? 1.0 : .9;
    const impact = mode === 'TWAP' ? 2.8 : mode === 'VWAP' ? 2.1 : 1.8;
    const timing = Math.max(0, Number(slippage) - spread - impact).toFixed(1);
    const sweep = [5000, 25000, 50000, 100000].map((size) => ({ size, value: Math.max(.8, 4.7 + (size / 25000) * modeFactor + participationAdj + (horizon < 10 ? 1.9 : 0) + benchmarkAdj + sideAdj).toFixed(1) }));
    const comparison = ['TWAP', 'VWAP', 'POV'].map((strategy) => { const factor = strategy === 'TWAP' ? 1.8 : strategy === 'VWAP' ? 1.35 : 1.05; const povAdj = strategy === 'POV' ? participationAdj : 0; return { strategy, value: Math.max(.8, 4.7 + scale * factor + povAdj + (horizon < 10 ? 1.9 : 0) + benchmarkAdj + sideAdj).toFixed(1) }; });
    const benchmarkMarks = [{ label: 'Arrival', value: baseSlippage }, { label: 'Session VWAP', value: baseSlippage - .6 }, { label: 'Close', value: baseSlippage + 1.1 }].map((item) => ({ ...item, value: Math.max(.8, item.value).toFixed(1) }));
    return { slippage, fill: Math.min(99.2, 96.4 + horizon / 12 - scale * .35).toFixed(1), cost: (Number(slippage) * quantity * .01).toFixed(0), sweep, comparison, benchmarkMarks, venueMix, checks, breakdown: [{ label: 'Spread', value: spread.toFixed(1), tone: 'teal' }, { label: 'Market impact', value: impact.toFixed(1), tone: 'orange' }, { label: 'Timing', value: timing, tone: 'red' }] };
  }, [benchmark, horizon, maxSpread, mode, participation, quantity, routePolicy, side]);

  const advanceReplay = () => setReplayIndex((index) => (index + 1) % prints.length);
  const recordRun = () => {
    const nextRun = run + 1;
    setRun(nextRun);
    setHistory((items) => [{ id: nextRun, strategy: mode, side, benchmark, slippage: result.slippage, fill: result.fill }, ...items].slice(0, 3));
  };
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand-mark">MF</div><nav className="side-nav" aria-label="Primary navigation">
      <button className="nav-item active" aria-label="Execution lab"><LineChart size={18}/><span>Lab</span></button><button className="nav-item" aria-label="Order book"><Layers3 size={18}/><span>Book</span></button><button className="nav-item" aria-label="Market replay"><Radio size={18}/><span>Replay</span></button><button className="nav-item" aria-label="Reports"><BarChart3 size={18}/><span>Reports</span></button>
    </nav><div className="sidebar-bottom"><button className="nav-item" aria-label="Settings"><Settings2 size={18}/><span>Setup</span></button><div className="avatar">AB</div></div></aside>
    <section className="workspace"><header className="topbar"><div className="breadcrumb"><span>MarketForge</span><b>/</b><strong>Execution lab</strong></div><div className="top-actions"><div className="status-dot"><i/> Replay data synced</div><button className="icon-button" aria-label="Help"><CircleHelp size={17}/></button><button className="icon-button" aria-label="Settings"><SlidersHorizontal size={17}/></button></div></header>
      <div className="content">
        <div className="page-heading"><div><div className="kicker"><Sparkles size={13}/> PAPER EXECUTION / PHASE 1</div><h1>Read the tape. <em>Route with intent.</em></h1><p>Reconstruct the market, pressure-test a schedule, and see the cost of every decision.</p></div><div className="session-chip"><i/> SIMULATION ONLY <ChevronDown size={14}/></div></div>
        <div className="instrument-bar panel"><div className="instrument-main"><div className="ticker">NVDA</div><div><div className="instrument-name">NVIDIA Corporation <span className="venue-tag">XNAS</span></div><div className="instrument-sub">US Equity · regular session · 09:30—16:00 ET</div></div></div><div className="instrument-price"><strong>182.42</strong><span className="positive"><ArrowUpRight size={14}/> +0.86%</span></div><div className="instrument-stats"><span>Bid <b>182.41</b></span><span>Ask <b>182.43</b></span><span>Spread <b>0.02</b></span></div></div>
        <div className="lab-grid"><section className="panel tape-panel"><div className="panel-header"><div><div className="section-label"><Activity size={14}/> Market reconstruction</div><h2>Spread &amp; mid-price</h2></div><div className="chart-actions"><div className="segmented">{['1m','5m','30m'].map((item)=><button key={item} className={window===item?'selected':''} onClick={()=>setWindow(item as '1m'|'5m'|'30m')}>{item}</button>)}</div><button className="run-button" onClick={advanceReplay}><Play size={13} fill="currentColor"/> Replay</button></div></div><div className="chart-wrap"><div className="chart-y-axis"><span>182.50</span><span>182.46</span><span>182.42</span><span>182.38</span><span>182.34</span></div><div className="chart-area"><div className="chart-grid-lines"><i/><i/><i/><i/><i/></div><svg viewBox="0 0 690 164" preserveAspectRatio="none" aria-label="Reconstructed mid-price chart"><defs><linearGradient id="areaFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#5de2c0" stopOpacity=".18"/><stop offset="100%" stopColor="#5de2c0" stopOpacity="0"/></linearGradient></defs><polyline points={chartPaths[window]+' 690,164 0,164'} fill="url(#areaFill)"/><polyline points={chartPaths[window]} fill="none" stroke="#63e6c3" strokeWidth="2.5"/><line x1="0" x2="690" y1="83" y2="83" stroke="#f2a65a" strokeDasharray="4 5"/><circle cx="690" cy="14" r="4" fill="#63e6c3"/></svg><div className="chart-x-axis">{chartTicks[window].map((tick)=><span key={tick}>{tick}</span>)}</div><div className="chart-legend"><span><i className="legend-dot"/> Mid-price</span><span><i className="legend-line"/> Arrival mid</span></div></div></div><div className="chart-footer"><span><Clock3 size={14}/> Fixture: NASDAQ ITCH sample · 06 Jun 2024</span><span>Last event <b>{activePrint[0]}.000 ET</b></span><span className="replay-progress">Replay {replayIndex + 1}/{prints.length}</span><span className="positive">+0.11% since arrival</span></div><div className="replay-inspector"><div><span className="eyebrow">Active event</span><strong>{activePrint[0]} · {activePrint[1].toUpperCase()}</strong></div><div><span className="replay-detail">{activePrint[3]} shares @ \${activePrint[2]}</span><span className="replay-venue">{activePrint[4]} venue</span></div></div></section>
          <section className="panel book-panel"><div className="panel-header compact"><div><div className="section-label"><BookOpen size={14}/> Reconstructed book</div><h2>Top of book</h2></div><span className="live-tag"><i/> LIVE REPLAY</span></div><div className="book-head"><span>Price</span><span>Size</span></div><div>{book.map(([price,size,side])=><div className={'book-row '+side} key={price as string}><span className="depth" style={{width:Math.min(92,(size as number)/10)+'%'}}/><span>{price as string}</span><span>{(size as number).toLocaleString()}</span></div>)}</div><div className="microprice"><span>Microprice</span><strong>182.425</strong><span className="positive">+0.005 bias</span></div><div className="venue-depth"><div className="venue-depth-head"><span>Venue snapshots</span><span>queue / latency</span></div>{venueQuotes.map(([venue,bid,ask,latency,queue])=><div className={'venue-quote '+(venue===activePrint[4]?'active-venue':'')} key={venue}><span className="venue-name"><i/>{venue}</span><span className="venue-bid">{bid}</span><span className="venue-ask">{ask}</span><span className="venue-queue">{queue}</span><span className="venue-latency">{latency}</span></div>)}</div></section></div>
        <div className="metrics-row"><Metric label="Arrival mid" value="$182.21" note="09:36:00.000 ET"/><Metric label="Quoted spread" value="2.0¢" note="1.10 bps · inside"/><Metric label="Book imbalance" value="+18.4%" note="Bid-side pressure" tone="good"/><Metric label="Realized volatility" value="12.8%" note="5 min annualized" tone="warn"/></div>
        <div className="lower-grid"><section className="panel tape-table-panel"><div className="panel-header compact"><div><div className="section-label"><TerminalSquare size={14}/> Event stream</div><h2>Recent prints <span className="muted-title">· {visiblePrints.length} shown</span></h2></div><div className="stream-filters segmented">{['All','Buys','Sells'].map((item)=><button key={item} className={printFilter===item?'selected':''} onClick={()=>setPrintFilter(item as 'All'|'Buys'|'Sells')}>{item}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Side</th><th>Price</th><th>Size</th><th>Venue</th></tr></thead><tbody>{visiblePrints.map(([time,side,price,size,venue])=><tr className={time === activePrint[0] ? 'active-print' : ''} key={time+price}><td className="mono">{time}</td><td><span className={'side-pill '+side}>{side==='buy'?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {side}</span></td><td className="mono">{price}</td><td className="mono">{size}</td><td><span className="venue-tag">{venue}</span></td></tr>)}</tbody></table></div></section>
          <section className="panel order-panel"><div className="panel-header compact"><div><div className="section-label"><Target size={14}/> Parent order</div><h2>Simulate an execution</h2></div><span className="order-id">PF-0042</span></div><div className="order-fields"><label>Instrument<input value="NVDA · NASDAQ" readOnly/></label><label>Side<select value={side} onChange={e=>setSide(e.target.value as 'Buy'|'Sell')}><option>Buy</option><option>Sell</option></select></label><label>Quantity<input type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value)||0)} min="100" step="100"/></label><label>Horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></label><label>Benchmark<select value={benchmark} onChange={e=>setBenchmark(e.target.value as 'Arrival'|'VWAP'|'Close')}><option value="Arrival">Arrival price</option><option value="VWAP">Session VWAP</option><option value="Close">Close</option></select></label><label>POV cap<select value={participation} onChange={e=>setParticipation(Number(e.target.value))}><option value={5}>5% ADV</option><option value={10}>10% ADV</option><option value={20}>20% ADV</option></select></label><label>Route<select value={routePolicy} onChange={e=>setRoutePolicy(e.target.value as 'Balanced'|'Queue-aware'|'Latency-aware')}><option>Balanced</option><option>Queue-aware</option><option>Latency-aware</option></select></label><label>Spread limit<select value={maxSpread} onChange={e=>setMaxSpread(Number(e.target.value))}><option value={2}>2.0¢</option><option value={3}>3.0¢</option><option value={5}>5.0¢</option></select></label></div><div className="strategy-toggle"><span>Schedule</span><div className="strategy-buttons"><button className={mode==='TWAP'?'selected':''} onClick={()=>setMode('TWAP')}>TWAP <small>even time</small></button><button className={mode==='VWAP'?'selected':''} onClick={()=>setMode('VWAP')}>VWAP <small>volume-aware</small></button><button className={mode==='POV'?'selected':''} onClick={()=>setMode('POV')}>POV <small>participation cap</small></button></div></div><button className="simulate-button" onClick={recordRun}><Zap size={15} fill="currentColor"/> Run paper simulation <span>⌘ ↵</span></button><div className="sim-result"><div><span>Projected slippage</span><strong>{result.slippage} bps</strong></div><div><span>Expected fill</span><strong>{result.fill}%</strong></div><div><span>Est. impact</span><strong>{'$'+result.cost}</strong></div></div></section></div>
        <section className="panel schedule-panel"><div className="panel-header compact"><div><div className="section-label"><Gauge size={14}/> Child order schedule</div><h2>{mode} slices <span className="muted-title">· run {String(run).padStart(2,'0')}</span></h2></div><div className="schedule-summary">{mode === 'POV' ? <span>{participation}% cap</span> : <span>6 slices</span>}<span>4,167 avg shares</span><span className="positive">Paper result ready</span></div></div><div className="schedule-track"><div className="track-line"/><div className="slice-row">{['09:36','09:39','09:42','09:45','09:48','09:51'].map((time,index)=><div className={'slice '+(index<3?'filled':'')} key={time}><div className="slice-dot"><span>{index<3?'✓':index+1}</span></div><div className="slice-time">{time}</div><div className="slice-qty">{index<3?'4,167':'—'}</div><div className={'slice-state '+(index<3?'done':'')}>{index<3?'filled':'queued'}</div></div>)}</div></div></section>
                <section className="panel guardrail-panel"><div className="panel-header compact"><div><div className="section-label"><ShieldCheck size={14}/> Pre-trade checks</div><h2>Route with the guardrails visible</h2></div><span className="ledger-count">{result.checks.filter((item) => item.value === 'PASS' || item.value === 'COVERED' || item.value === 'BALANCED' || item.value === 'QUEUE-AWARE' || item.value === 'LATENCY-AWARE').length}/3 clear</span></div><div className="guardrail-grid">{result.checks.map((item) => <div className={'guardrail-card '+item.tone} key={item.label}><div className="guardrail-top"><strong>{item.label}</strong><span>{item.value}</span></div><div className="guardrail-detail">{item.detail}</div></div>)}</div></section><section className="panel attribution-panel"><div className="panel-header compact"><div><div className="section-label"><Activity size={14}/> Execution report</div><h2>Where the cost comes from</h2></div><span className="report-badge">{benchmark.toUpperCase()} BENCHMARK <span>· {side} / {mode}</span></span></div><div className="attribution-grid"><div className="attribution-chart"><div className="attribution-total"><span>Projected slippage</span><strong>{result.slippage} <small>bps</small></strong></div><div className="stacked-bar">{result.breakdown.map((item)=><div key={item.label} className={'stack-segment '+item.tone} style={{width:(Number(item.value)/Number(result.slippage)*100)+'%'}} title={item.label+' '+item.value+' bps'}/>)}</div><div className="attribution-legend">{result.breakdown.map((item)=><span key={item.label}><i className={item.tone}/>{item.label}<b>{item.value} bps</b></span>)}</div></div><div className="venue-mix"><div className="mix-heading"><span>Expected venue mix · {routePolicy}</span><span>Fill {result.fill}%</span></div>{result.venueMix.map(([venue,share,tone])=><div className="mix-row" key={venue}><span className="mix-name"><i className={tone}/>{venue}</span><div className="mix-track"><span className={tone} style={{width:share}}/></div><b>{share}</b></div>)}</div><div className="report-note"><Zap size={15}/><div><strong>{side} {mode} is {mode === 'TWAP' ? 'time-even' : mode === 'VWAP' ? 'volume-aware' : 'participation-capped'} against {benchmark.toLowerCase()}.</strong><span>Change quantity or horizon to see the simulated attribution update.</span></div></div></div></section>
                <section className="panel benchmark-panel"><div className="panel-header compact"><div><div className="section-label"><BarChart3 size={14}/> Benchmark attribution</div><h2>Same schedule, different reference</h2></div><span className="ledger-count">{side} · {mode} · {quantity.toLocaleString()} shares</span></div><div className="benchmark-grid">{result.benchmarkMarks.map((item) => <div className={'benchmark-card '+(item.label === (benchmark === 'VWAP' ? 'Session VWAP' : benchmark) ? 'active-benchmark' : '')} key={item.label}><div className="benchmark-top"><strong>{item.label}</strong>{item.label === (benchmark === 'VWAP' ? 'Session VWAP' : benchmark) && <span>SELECTED</span>}</div><div className="benchmark-value">{item.value}<small>bps</small></div><div className="benchmark-copy">Modeled slippage against this reference</div></div>)}</div><div className="benchmark-note"><span>↗</span> Benchmark choice changes the interpretation of the same paper fill; arrival remains the neutral reference.</div></section><section className="panel compare-panel"><div className="panel-header compact"><div><div className="section-label"><Target size={14}/> Strategy compare</div><h2>TWAP vs VWAP vs POV</h2></div><span className="ledger-count">{side} · {benchmark} benchmark</span></div><div className="compare-grid">{result.comparison.map((item) => <div className={'compare-card '+(item.strategy===mode?'active-compare':'')} key={item.strategy}><div className="compare-top"><strong>{item.strategy}</strong>{item.strategy===mode && <span>ACTIVE</span>}</div><div className="compare-value">{item.value}<small>bps</small></div><div className="compare-copy">{item.strategy === 'TWAP' ? 'Even time slices' : item.strategy === 'VWAP' ? 'Volume-aware slices' : 'Participation capped'}</div></div>)}</div><div className="compare-delta"><span>Simulated edge</span><strong>{(Number(result.comparison[0].value)-Number(result.comparison[1].value)).toFixed(1)} bps</strong><small>{Number(result.comparison[1].value) < Number(result.comparison[0].value) ? 'VWAP is lighter on this fixture' : 'TWAP is lighter on this fixture'}</small></div></section>
        <section className="panel sensitivity-panel"><div className="panel-header compact"><div><div className="section-label"><Activity size={14}/> Size sensitivity</div><h2>Slippage by order size</h2></div><span className="ledger-count">{benchmark} benchmark · {mode}</span></div><div className="sensitivity-grid">{result.sweep.map((item) => <div className="sensitivity-card" key={item.size}><div className="sensitivity-label">{item.size >= 1000 ? (item.size / 1000) + 'k' : item.size} shares</div><div className="sensitivity-bar"><span style={{width: Math.min(100, Number(item.value) / 12 * 100) + '%'}}/></div><div className="sensitivity-value">{item.value}<small>bps</small></div></div>)}</div><div className="sensitivity-note"><span>↗</span> Larger clips spend more of the visible book before the schedule can adapt.</div></section>
        <section className="panel ledger-panel"><div className="panel-header compact"><div><div className="section-label"><TerminalSquare size={14}/> Experiment ledger</div><h2>Recent paper runs</h2></div><span className="ledger-count">{history.length}/3 pinned</span></div>{history.length === 0 ? <div className="ledger-empty"><span>⌁</span><div><strong>No runs pinned yet</strong><p>Run a paper simulation to keep its result here for comparison.</p></div></div> : <div className="ledger-list">{history.map((item) => <div className="ledger-row" key={item.id}><span className="ledger-id">#{String(item.id).padStart(2,'0')}</span><span className="ledger-strategy"><b>{item.side} {item.strategy}</b><small>{item.benchmark} benchmark</small></span><span className="ledger-stat"><small>Slippage</small><b>{item.slippage} bps</b></span><span className="ledger-stat"><small>Fill</small><b className="positive">{item.fill}%</b></span><span className="ledger-state">PAPER</span></div>)}</div>}</section>
        <footer className="roadmap-footer"><div><ShieldCheck size={14}/><strong>Paper/simulation only</strong><span>· No broker connection or live routing</span></div><div>Phase 1 foundation <span className="footer-dot"/> Next: adaptive venue weights, live calibration</div></footer>
      </div>
    </section>
  </main>;
}























