'use client';

import { useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, BookOpen, ChevronDown, CircleHelp, Clock3, Gauge, Layers3, LineChart, Play, Radio, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, TerminalSquare, Zap } from 'lucide-react';

const prints = [
  ['09:41:00','buy','182.41','420','XNAS'],['09:41:03','sell','182.40','185','BATS'],
  ['09:41:07','buy','182.42','760','XNAS'],['09:41:13','buy','182.43','220','EDGX'],
  ['09:41:18','sell','182.42','510','XNAS'],['09:41:25','buy','182.44','340','ARCX'],
];
const book = [['182.46',530,'ask'],['182.45',286,'ask'],['182.44',712,'ask'],['182.43',460,'ask'],['182.42',890,'mid'],['182.41',650,'bid'],['182.40',480,'bid'],['182.39',920,'bid'],['182.38',760,'bid']];
const chartPath = '0,148 46,135 92,141 138,115 184,122 230,96 276,104 322,79 368,88 414,60 460,66 506,38 552,50 598,25 644,32 690,14';

function Metric({ label, value, note, tone = '' }: { label: string; value: string; note: string; tone?: string }) {
  return <div className="metric-card"><div className="eyebrow">{label}</div><div className={'metric-value ' + tone}>{value}</div><div className="metric-note">{note}</div></div>;
}

export default function Home() {
  const [window, setWindow] = useState('5m');
  const [mode, setMode] = useState<'TWAP'|'VWAP'>('TWAP');
  const [quantity, setQuantity] = useState(25000);
  const [horizon, setHorizon] = useState(15);
  const [run, setRun] = useState(1);
  const result = useMemo(() => {
    const scale = Math.min(quantity / 25000, 3);
    const slippage = (4.7 + scale * (mode === 'TWAP' ? 1.8 : 1.35) + (horizon < 10 ? 1.9 : 0)).toFixed(1);
    return { slippage, fill: Math.min(99.2, 96.4 + horizon / 12 - scale * .35).toFixed(1), cost: (Number(slippage) * quantity * .01).toFixed(0) };
  }, [horizon, mode, quantity]);

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand-mark">MF</div><nav className="side-nav" aria-label="Primary navigation">
      <button className="nav-item active" aria-label="Execution lab"><LineChart size={18}/><span>Lab</span></button><button className="nav-item" aria-label="Order book"><Layers3 size={18}/><span>Book</span></button><button className="nav-item" aria-label="Market replay"><Radio size={18}/><span>Replay</span></button><button className="nav-item" aria-label="Reports"><BarChart3 size={18}/><span>Reports</span></button>
    </nav><div className="sidebar-bottom"><button className="nav-item" aria-label="Settings"><Settings2 size={18}/><span>Setup</span></button><div className="avatar">AB</div></div></aside>
    <section className="workspace"><header className="topbar"><div className="breadcrumb"><span>MarketForge</span><b>/</b><strong>Execution lab</strong></div><div className="top-actions"><div className="status-dot"><i/> Replay data synced</div><button className="icon-button" aria-label="Help"><CircleHelp size={17}/></button><button className="icon-button" aria-label="Settings"><SlidersHorizontal size={17}/></button></div></header>
      <div className="content">
        <div className="page-heading"><div><div className="kicker"><Sparkles size={13}/> PAPER EXECUTION / PHASE 1</div><h1>Read the tape. <em>Route with intent.</em></h1><p>Reconstruct the market, pressure-test a schedule, and see the cost of every decision.</p></div><div className="session-chip"><i/> SIMULATION ONLY <ChevronDown size={14}/></div></div>
        <div className="instrument-bar panel"><div className="instrument-main"><div className="ticker">NVDA</div><div><div className="instrument-name">NVIDIA Corporation <span className="venue-tag">XNAS</span></div><div className="instrument-sub">US Equity · regular session · 09:30—16:00 ET</div></div></div><div className="instrument-price"><strong>182.42</strong><span className="positive"><ArrowUpRight size={14}/> +0.86%</span></div><div className="instrument-stats"><span>Bid <b>182.41</b></span><span>Ask <b>182.43</b></span><span>Spread <b>0.02</b></span></div></div>
        <div className="lab-grid"><section className="panel tape-panel"><div className="panel-header"><div><div className="section-label"><Activity size={14}/> Market reconstruction</div><h2>Spread &amp; mid-price</h2></div><div className="chart-actions"><div className="segmented">{['1m','5m','30m'].map((item)=><button key={item} className={window===item?'selected':''} onClick={()=>setWindow(item)}>{item}</button>)}</div><button className="run-button" onClick={()=>setRun(run+1)}><Play size={13} fill="currentColor"/> Replay</button></div></div><div className="chart-wrap"><div className="chart-y-axis"><span>182.50</span><span>182.46</span><span>182.42</span><span>182.38</span><span>182.34</span></div><div className="chart-area"><div className="chart-grid-lines"><i/><i/><i/><i/><i/></div><svg viewBox="0 0 690 164" preserveAspectRatio="none" aria-label="Reconstructed mid-price chart"><defs><linearGradient id="areaFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#5de2c0" stopOpacity=".18"/><stop offset="100%" stopColor="#5de2c0" stopOpacity="0"/></linearGradient></defs><polyline points={chartPath+' 690,164 0,164'} fill="url(#areaFill)"/><polyline points={chartPath} fill="none" stroke="#63e6c3" strokeWidth="2.5"/><line x1="0" x2="690" y1="83" y2="83" stroke="#f2a65a" strokeDasharray="4 5"/><circle cx="690" cy="14" r="4" fill="#63e6c3"/></svg><div className="chart-x-axis"><span>09:36:00</span><span>09:37:30</span><span>09:39:00</span><span>09:40:30</span><span>09:42:00</span></div><div className="chart-legend"><span><i className="legend-dot"/> Mid-price</span><span><i className="legend-line"/> Arrival mid</span></div></div></div><div className="chart-footer"><span><Clock3 size={14}/> Fixture: NASDAQ ITCH sample · 06 Jun 2024</span><span>Last event <b>09:42:00.841</b></span><span className="positive">+0.11% since arrival</span></div></section>
          <section className="panel book-panel"><div className="panel-header compact"><div><div className="section-label"><BookOpen size={14}/> Reconstructed book</div><h2>Top of book</h2></div><span className="live-tag"><i/> LIVE REPLAY</span></div><div className="book-head"><span>Price</span><span>Size</span></div><div>{book.map(([price,size,side])=><div className={'book-row '+side} key={price as string}><span className="depth" style={{width:Math.min(92,(size as number)/10)+'%'}}/><span>{price as string}</span><span>{(size as number).toLocaleString()}</span></div>)}</div><div className="microprice"><span>Microprice</span><strong>182.425</strong><span className="positive">+0.005 bias</span></div></section></div>
        <div className="metrics-row"><Metric label="Arrival mid" value="$182.21" note="09:36:00.000 ET"/><Metric label="Quoted spread" value="2.0¢" note="1.10 bps · inside"/><Metric label="Book imbalance" value="+18.4%" note="Bid-side pressure" tone="good"/><Metric label="Realized volatility" value="12.8%" note="5 min annualized" tone="warn"/></div>
        <div className="lower-grid"><section className="panel tape-table-panel"><div className="panel-header compact"><div><div className="section-label"><TerminalSquare size={14}/> Event stream</div><h2>Recent prints</h2></div><button className="text-button">View all <ArrowUpRight size={13}/></button></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Side</th><th>Price</th><th>Size</th><th>Venue</th></tr></thead><tbody>{prints.map(([time,side,price,size,venue])=><tr key={time+price}><td className="mono">{time}</td><td><span className={'side-pill '+side}>{side==='buy'?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {side}</span></td><td className="mono">{price}</td><td className="mono">{size}</td><td><span className="venue-tag">{venue}</span></td></tr>)}</tbody></table></div></section>
          <section className="panel order-panel"><div className="panel-header compact"><div><div className="section-label"><Target size={14}/> Parent order</div><h2>Simulate an execution</h2></div><span className="order-id">PF-0042</span></div><div className="order-fields"><label>Instrument<input value="NVDA · NASDAQ" readOnly/></label><label>Side<select defaultValue="Buy"><option>Buy</option><option>Sell</option></select></label><label>Quantity<input type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value)||0)} min="100" step="100"/></label><label>Horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></label></div><div className="strategy-toggle"><span>Schedule</span><div className="strategy-buttons"><button className={mode==='TWAP'?'selected':''} onClick={()=>setMode('TWAP')}>TWAP <small>even time</small></button><button className={mode==='VWAP'?'selected':''} onClick={()=>setMode('VWAP')}>VWAP <small>volume-aware</small></button></div></div><button className="simulate-button" onClick={()=>setRun(run+1)}><Zap size={15} fill="currentColor"/> Run paper simulation <span>⌘ ↵</span></button><div className="sim-result"><div><span>Projected slippage</span><strong>{result.slippage} bps</strong></div><div><span>Expected fill</span><strong>{result.fill}%</strong></div><div><span>Est. impact</span><strong>{'$'+result.cost}</strong></div></div></section></div>
        <section className="panel schedule-panel"><div className="panel-header compact"><div><div className="section-label"><Gauge size={14}/> Child order schedule</div><h2>{mode} slices <span className="muted-title">· run {String(run).padStart(2,'0')}</span></h2></div><div className="schedule-summary"><span>6 slices</span><span>4,167 avg shares</span><span className="positive">Paper result ready</span></div></div><div className="schedule-track"><div className="track-line"/><div className="slice-row">{['09:36','09:39','09:42','09:45','09:48','09:51'].map((time,index)=><div className={'slice '+(index<3?'filled':'')} key={time}><div className="slice-dot"><span>{index<3?'✓':index+1}</span></div><div className="slice-time">{time}</div><div className="slice-qty">{index<3?'4,167':'—'}</div><div className={'slice-state '+(index<3?'done':'')}>{index<3?'filled':'queued'}</div></div>)}</div></div></section>
        <footer className="roadmap-footer"><div><ShieldCheck size={14}/><strong>Paper/simulation only</strong><span>· No broker connection or live routing</span></div><div>Phase 1 foundation <span className="footer-dot"/> Next: venue models, POV, arrival-price attribution</div></footer>
      </div>
    </section>
  </main>;
}

